<?php

echo "<h1>Hello!</h1>";

echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary']);

if ($users->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <p id='results'></p>
        <thead class="thead-light">
            <tr>
                <th>User id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3" id='check' value="check" >Users quantity: <?php echo $users->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($users as $user) { ?>
                <tr>
                    <td><?php echo $user->user_id; ?></td>
                    <td><?php echo $user->username; ?></td>
                    <td><?php echo $user->email; ?></td>
                    <td><?php echo $user->description; ?></td>
                    <td>
                    <?php echo $this->tag->linkTo(["index/edit/".$user->user_id, "Edit", 'class' => 'btn btn-primary']); ?>
                    <?php echo $this->tag->linkTo(["index/delete/".$user->user_id, "Delete", 'class' => 'btn btn-primary']); ?>
                </td>

                </tr>
            <?php } ?>
        </tbody>
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="../../../public/assests/js/script.js" rel="text/javascript"></script>
<?php
}
